services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: foto_foireuse_db
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: TEST
    ports:
      - "5432:5432"
    volumes:
      - db-pgdata:/var/lib/postgresql/data

  back:
    working_dir: /djangoProject
    build:
      context: djangoProject
      dockerfile: Dockerfile
    volumes:
      - ./djangoProject:/djangoProject
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: curl -f http://localhost:8000/api/
      interval: 1m00s
    environment:
      DATABASE_URL: postgres://USER:TEST@db/foto_foireuse_db

  web:
    build:
      context: ./fotofront
      dockerfile: Dockerfile
    volumes:
      - ./fotofront:/app
    depends_on:
      - back
    ports:
      - 12803:80

volumes:
  db-pgdata:
