version: '3.8'
services:
  db:
    image: postgres:latest
    #volumes:
    #  - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: foto_foireuse_db
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: TEST
    ports:
      - "5432:5432"

  web:
    working_dir: /djangoProject
    build:
      context: djangoProject
      dockerfile: Dockerfile
    volumes:
      - ./djangoProject:/djangoProject
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    #command: python manage.py runserver 0.0.0.0:8000
    #volumes:
      #- .:/FotoFoireuseDjango
    ports:
      - "8000:8000"
    depends_on:
      - db
    healthcheck:
      test: curl -f http://localhost:8000/api/
      interval: 1m00s
    environment:
      DATABASE_URL: postgres://USER:TEST@db/foto_foireuse_db
      PYTHONPATH: /djangoProject:$PYTHONPATH
