### health test
GET http://localhost:8000/api/

### register
POST http://localhost:8000/api/user/register/
content-type: application/json

{
    "username": "dd64",
    "password": "dev",
    "email": "dd64@dev.fr"
}

### login
POST http://localhost:8000/api/user/login/
content-type: application/json

{
    "username": "dd64",
    "password": "dev"
}

### refresh token
POST http://localhost:8000/api/token/refresh/
content-type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNjM2NjY5NiwiaWF0IjoxNzE2MjgwMjk2LCJqdGkiOiJmOTg2ZGIzNjgzYTc0NmMyYmNmN2Q1YjYzZWQ2MzVjMSIsInVzZXJfaWQiOjF9.97FXKcEzHKcgmw3UGwueHXe117wxFyvhyLcSa-23G6Y"
}

### test
GET http://localhost:8000/api/user/test/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0ODU5ODQ2LCJpYXQiOjE3MTQ4NTk1NDYsImp0aSI6ImMxZTdiNDk0M2NmZDRhMGY5YWUzZmJhMzk0YzE3ODBkIiwidXNlcl9pZCI6MX0.LVcBISVQLFmUJszeDqvVcuUMK-W4AI1RY6uaj9hamwc

###
GET http://localhost:8000/api/user/test/
Authorization: Barear eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0ODYwNTYxLCJpYXQiOjE3MTQ4NjAyNjEsImp0aSI6IjlhMjJkZmYxZTJkYTRlNmU5YjE1NGQyMDViNDFiMWM3IiwidXNlcl9pZCI6MX0.AqnTM5Pixiqc0SjSsL2tIKM0FSqRJQaAKEkiLMmBshE
