### login
POST http://localhost:8000/api/user/login/
content-type: application/json

{
    "username": "dd64",
    "password": "dev"
}

###
GET http://localhost:8000/api/concours/1/photos/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MzAzNjU0LCJpYXQiOjE3MTYzMDMzNTQsImp0aSI6ImQyZmMxYTg2Yzg0OTRlYTFhMTBjNmIyMWY3N2Q5YjFlIiwidXNlcl9pZCI6MX0.SmGoinLDDPreXidye4R06cgh1Dwh71BgDlyrENruN6c
content-type: application/json

{
  "texte": "teettt"
}


### test
POST http://localhost:8000/api/conc
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE0ODY0NzEwLCJpYXQiOjE3MTQ4NjQ0MTAsImp0aSI6ImNjZDI1NDc3MGM4ODRhZWE5NWRmYjg4NzRlZDJjNGE0IiwidXNlcl9pZCI6MX0.jHN-rDX89jWIbexJmupjONNyDOFz8QKH0kAqUGShz8A
content-type: application/json

{
    "texte": "test"
}
