###
POST http://dd64.fr:8000/api/user/register/
Content-Type: application/json

{
    "username": "dd64",
    "password": "jeTest",
    "first_name": "Dodo",
    "last_name": "le pedo",
    "email": "dodoLePedo@gmail.fr",
    "sexe":"NB"
}

###
POST http://dd64.fr:8000/api/user/login/
Content-Type: application/json

{
    "username": "dd64",
    "password": "jeTest"
}

### test
GET http://dd64.fr:8000/api/concours/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MzcxNjg2LCJpYXQiOjE3MTYzNzA5NjEsImp0aSI6IjE4YTdmMDhmNDQ3NTRiYjY4OTFlMGQyZTk5M2UxNjQxIiwidXNlcl9pZCI6MX0.SAiaFV0GmXi6tsHBC1uikDQVytCESdZFLMdcaMO-Cfc


###
POST http://dd64.fr:8000/api/token/refresh/
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNjQ1NzM2MSwiaWF0IjoxNzE2MzcwOTYxLCJqdGkiOiI4N2ZkMjZhYjZiNmQ0NGYyOWU5YmRhYTZlNGE1NWEwZCIsInVzZXJfaWQiOjF9.xoFhIYBOR2YoMvaET-eMRn1O9D0bOy2jvaU5Ei76eds"
  }

###
POST http://dd64.fr:8000/api/user/logout/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzE2MzcxOTYzLCJpYXQiOjE3MTYzNzA5NjEsImp0aSI6IjcxNTUyNWI5MTdkZjQzOTRiOTljZTYxZDYzMmY3MWZlIiwidXNlcl9pZCI6MX0.igw8_Qth3AkKbzJzDEylsmMsWaVV61zbyBzM_upYseI
Content-Type: application/json

{
    "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTcxNjQ1NzM2MSwiaWF0IjoxNzE2MzcwOTYxLCJqdGkiOiI4N2ZkMjZhYjZiNmQ0NGYyOWU5YmRhYTZlNGE1NWEwZCIsInVzZXJfaWQiOjF9.xoFhIYBOR2YoMvaET-eMRn1O9D0bOy2jvaU5Ei76eds"
  }