name: deployment
on:
    push:
        branches:
        - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        run: |
          ssh -i ${{ secrets.DEPLOYMENT_KEY }} dd64@dd64.fr "cd /path/to/your/application && git pull"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOYMENT_KEY }}